// FBR DI API v1.12 §7 "Sales Error Codes": the spec's plain description of each code (BRIEF_MSG_DESC, shortened),
// shown next to FBR's own reply so the user knows what to fix.
const SALES_ERRORS = {
    '0001': 'Seller is not registered for sales tax — check the seller NTN in the client settings',
    '0002': 'Buyer NTN must be 7 or 9 digits, or a 13-digit registration / CNIC',
    '0003': 'Invoice type is not valid',
    '0005': 'Invoice date must be in YYYY-MM-DD format',
    '0006': 'Sales invoice does not exist for this withholding (STWH)',
    '0007': 'The selected invoice type does not match the registration number',
    '0008': 'ST withheld at source must be zero or equal to the sales tax',
    '0009': 'Buyer registration number is missing',
    '0010': 'Buyer name is missing',
    '0011': 'Invoice type is missing',
    '0012': 'Buyer registration type is missing',
    '0013': 'Sale type is missing or not valid',
    '0018': 'Sales tax / FED in ST mode is missing',
    '0019': 'HS code is missing',
    '0020': 'Rate is missing',
    '0021': 'Value of sales excl. ST / quantity is missing',
    '0022': 'ST withheld at source is missing',
    '0023': 'Sales tax is missing',
    '0024': 'Sales tax withheld is missing',
    '0026': 'A debit note needs the original FBR invoice number',
    '0027': 'A debit note needs a reason',
    '0028': 'Reason "Others" needs remarks',
    '0029': 'The note date must be on or after the original invoice date',
    '0030': 'Unregistered distributor type is not allowed before the cut-off date',
    '0031': 'Sales tax is missing',
    '0032': 'Withholding (STWH) can only be created by Government / FTN holders',
    '0034': 'A debit / credit note is only allowed within 180 days of the original invoice',
    '0035': 'The note date must be on or after the original invoice date',
    '0036': 'Notes total more than the original invoice\'s value of sales',
    '0037': 'Notes total more than the original invoice\'s ST withheld',
    '0039': 'For registered users the withholding invoice must match the sale invoice',
    '0041': 'Invoice number is missing',
    '0042': 'Invoice date is missing',
    '0043': 'Invoice date is not valid',
    '0044': 'HS code is missing',
    '0046': 'Rate is missing — give a rate allowed for the sale type',
    '0050': 'For cotton ginners, ST withheld must be equal to the sales tax or zero',
    '0052': 'HS code does not match the sale type — choose a valid HS code for this sale type',
    '0053': 'Buyer registration type is not valid',
    '0055': 'ST withheld as withholding agent is missing or not valid',
    '0056': 'Buyer does not exist in the steel sector',
    '0057': 'The original invoice for this debit / credit note does not exist',
    '0058': 'Self-invoicing is not allowed — buyer and seller registration are the same',
    '0064': 'A credit note is already added to this invoice',
    '0067': 'Debit note sales tax is more than the original invoice\'s sales tax',
    '0068': 'Credit note sales tax is less than the original invoice\'s, for the rate',
    '0070': 'Withholding (STWH) is allowed only for registered users',
    '0071': 'Credit notes are allowed only for specific users',
    '0073': 'Sale origination province of the supplier is missing',
    '0074': 'Destination of supply (buyer province) is missing',
    '0077': 'SRO / Schedule number is missing — pick it from FBR\'s list on the item\'s tax rule',
    '0078': 'Item serial number is missing — pick it from FBR\'s list on the item\'s tax rule',
    '0079': 'Above Rs 20,000 the 5% rate is not allowed',
    '0080': 'Further tax is missing',
    '0081': '"Input credit not allowed" is missing',
    '0082': 'Seller is not registered for sales tax',
    '0083': 'Seller registration number does not match',
    '0085': 'Total value of sales is missing (PFAD only)',
    '0086': 'Not an EFS licence holder who imported compressor scrap in the last 12 months',
    '0087': 'Petroleum levy rates are not set up properly',
    '0088': 'Invoice number may only contain letters, numbers and a hyphen in between (e.g. Inv-001)',
    '0089': 'FED charged is missing',
    '0090': 'Fixed / notified value or retail price is missing — set the retail price on the item\'s tax rule',
    '0091': 'Extra tax must be empty for this sale type — remove the item\'s Extra Tax',
    '0092': 'Sale type is missing',
    '0093': 'This sale type is not allowed for manufacturers',
    '0095': 'Extra tax is missing',
    '0096': 'For this HS code only the KWH unit is allowed',
    '0097': 'The unit must be KG',
    '0098': 'Quantity / electricity units are missing',
    '0099': 'The unit (UOM) is not allowed for this HS code — use the unit FBR gives for the HS code',
    '0100': 'Registered users may use only the cotton ginners sale type here',
    '0101': 'Use the Toll Manufacturing sale type for the steel sector',
    '0102': 'Sales tax does not match the 3rd schedule formula (retail price × rate)',
    '0103': 'Calculated tax for potassium chlorate does not match',
    '0104': 'Sales tax does not match the rate — it must be rate × value',
    '0105': 'Sales tax for the quantity is not correct (rate with rupees per unit)',
    '0106': 'Buyer is not registered for sales tax',
    '0107': 'Buyer registration number does not match',
    '0108': 'Seller registration number / NTN is not valid',
    '0109': 'Wrong invoice type selected',
    '0111': 'Wrong purchase type selected',
    '0113': 'Date must be in YYYY-MM-DD format',
    '0300': 'A number field has an invalid value',
    '0401': 'The seller NTN / CNIC has no valid FBR token — check the client\'s token and NTN',
    '0402': 'The buyer NTN / CNIC has no valid FBR token',
};

const errorHint = code => SALES_ERRORS[String(code || '').padStart(4, '0')] || '';

module.exports = { SALES_ERRORS, errorHint };
